# transcript/Makefile.bsd
#
# Copyright 1985,1987 (C) Adobe Systems Incorporated. All rights reserved.
# GOVERNMENT END USERS: See notice of rights in Notice file in release directory.
# RCSID: $Header: Makefile.bsd,v 2.2 87/11/17 16:53:10 byron Rel $
#
# to install transcript:
#
#	(Once for your system)
#		bsd
#		edit config & printer
#		make programs
#
#		(become super-user)
#		make install		( install files in system dirs )
#
#	(For each PostScript/TranScript printer)
#		cd etc
#		(become super-user)
#		mkprinter PRINTER TTY
#

explain:
	@cat doc/make.notes

programs:
	. ./config; cd lib; make ${MFLAGS} programs
	. ./config; cd man; make ${MFLAGS} programs
	. ./config; cd sh;  make ${MFLAGS} programs
	. ./config; cd src; \
		sed -c s,SETCFLAGS,"$$SETCFLAGS",g <Make.proto >Makefile; \
		make ${MFLAGS} programs

install:
	-. ./config; rm -rf $$PSLIBDIR.old
	-. ./config; mv $$PSLIBDIR $$PSLIBDIR.old
	-. ./config; mkdir $$PSLIBDIR; chown $$OWNER $$PSLIBDIR; \
		chgrp $$GROUP $$PSLIBDIR; chmod 755 $$PSLIBDIR
	. ./config; cd src; make ${MFLAGS} install
	. ./config; cd sh;  make ${MFLAGS} install
	. ./config; cd lib; make ${MFLAGS} install
	. ./config; cd man; make ${MFLAGS} install

clean:
	rm -f *BAK *CKP .emacs_[0-9]*

cleanall: clean
	cd etc; make ${MFLAGS} clean
	cd lib; make ${MFLAGS} clean
	cd man; make ${MFLAGS} clean
	cd  sh; make ${MFLAGS} clean
	cd src; make ${MFLAGS} clean
